services:
  - type: web
    name: partner-top-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/main.py
    envVars:
      - key: API_TOKEN
        sync: false
autoDeployTrigger: commit
